steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg SITE_URL="${_SITE_URL}" \
          -t gcr.io/artcompiler-marketing/www:$COMMIT_SHA \
          .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/artcompiler-marketing/www:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - www
      - '--platform=managed'
      - '--image=gcr.io/artcompiler-marketing/www:$COMMIT_SHA'
      - '--labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--allow-unauthenticated'
    id: Deploy
    entrypoint: gcloud

images:
  - 'gcr.io/artcompiler-marketing/www:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _DEPLOY_REGION: us-central1
  _SITE_URL: https://graffiticode.org

tags:
  - graffiticode-www
